name: OptEco
version: 1.3b
api-version: 1.15
main: me.playernguyen.OptEco
author: Player_Nguyen
softdepend:
  - PlaceholderAPI

commands:
  opteco:
    usage: /opteco help
  points:
    usage: /opteco help